In [1]:
import pandas as pd
import os

base_path = '/Users/hiroyukiinoue/Documents/Python/Raschka/aclImdb'
labels = {'pos': 1, 'neg': 0}
df = pd.DataFrame()
for s in ('test', 'train'):
    for l in ('pos', 'neg'):
        path = os.path.join(base_path, s, l)
        for file in os.listdir(path):
            with open(os.path.join(path, file), 'r', encoding='utf-8') as infile:
                txt = infile.read()
                df = df.append([[txt, labels[l]]], ignore_index=True)

In [2]:
df.head(5)

0  1
0  I went and saw this movie last night after bei...  1
1  Actor turned director Bill Paxton follows up h...  1
2  As a recreational golfer with some knowledge o...  1
3  I saw this film in a sneak preview, and it is ...  1
4  Bill Paxton has taken the true story of the 19...  1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
0    50000 non-null object
1    50000 non-null int64
dtypes: int64(1), object(1)
memory usage: 781.3+ KB


In [4]:
import numpy as np
df = df.reindex(np.random.permutation(df.index))
df.to_csv('movie_data.csv', index=False, encoding='utf-8')

In [5]:
np.random.permutation(np.arange(10))

array([3, 4, 7, 6, 9, 8, 2, 1, 5, 0])

In [6]:
df.head(10)

0  1
43867  I was skeptical when I first saw the Calvin Kl...  0
19166  I'm sorry to say that this movies was one of t...  0
33404  I went to the cinema with two of my friends, a...  1
6409   I just watched this film at an advanced screen...  1
4336   There is really no way to compare this motion ...  1
35063  This is a film that everyone should watch. Qui...  1
17778  Terrible writing, highly contrived, from a "do...  0
45189  If you like to see animals being skinned alive...  0
14921  Zzzzzzzzzzzz. This one came directly from the ...  0
48425  Movie didn't have much plot and was uninterest...  0

In [7]:
df = pd.read_csv('movie_data.csv', encoding='utf-8')
df.columns = ['review', 'sentiment']
df.head(10)

review  sentiment
0  I was skeptical when I first saw the Calvin Kl...          0
1  I'm sorry to say that this movies was one of t...          0
2  I went to the cinema with two of my friends, a...          1
3  I just watched this film at an advanced screen...          1
4  There is really no way to compare this motion ...          1
5  This is a film that everyone should watch. Qui...          1
6  Terrible writing, highly contrived, from a "do...          0
7  If you like to see animals being skinned alive...          0
8  Zzzzzzzzzzzz. This one came directly from the ...          0
9  Movie didn't have much plot and was uninterest...          0

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
docs = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining and the weather is sweet'])
bag = count.fit_transform(docs)

In [9]:
count.vocabulary_

{'and': 0, 'is': 1, 'shining': 2, 'sun': 3, 'sweet': 4, 'the': 5, 'weather': 6}

In [10]:
print(bag.toarray())

[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [11]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
np.set_printoptions(precision=2)
print(count.vocabulary_)
print(tfidf.fit_transform(bag).toarray())

{'the': 5, 'sun': 3, 'is': 1, 'shining': 2, 'weather': 6, 'sweet': 4, 'and': 0}
[[ 0.    0.43  0.56  0.56  0.    0.43  0.  ]
 [ 0.    0.43  0.    0.    0.56  0.43  0.56]
 [ 0.4   0.48  0.31  0.31  0.31  0.48  0.31]]


In [12]:
df.loc[0, 'review'][-200:]

" entertaining scene -- specifically the moment when Johnny Whitworth licked Katherine Heigl's face -- and if you can tell me what that scene had to do with all the rest of the story more power to you."

In [47]:
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', ' ', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(D|P)', text)
    return text
print(preprocessor(df.loc[0, 'review'][-200:]))

 I see it second time round, I don't laugh all that much, but no matter how many times I see Dads Army, I laugh many times in an episode.  Best Episode: The Road to Banu, series 1, episode 7


In [14]:
df.loc[0, 'review'][-200:]

" entertaining scene -- specifically the moment when Johnny Whitworth licked Katherine Heigl's face -- and if you can tell me what that scene had to do with all the rest of the story more power to you."